import AboutContainer from "@/components/about";
import Layout from "@/components/layout";
import Head from "next/head";
import React from "react";

function About() {
  return (
    <Layout>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AboutContainer />
    </Layout>
  );
}

export default About;
