import Layout from "@/components/layout";
import ProjectsContainer from "@/components/projects";
import Head from "next/head";
import React from "react";

function Projects() {
  return (
    <Layout>
      <Head>
        <title>Elvin Shahsuvarli | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProjectsContainer/>
    </Layout>
  );
}

export default Projects;
